---
- name: Install bind9 packages
  apt:
    name:
      - bind9
      # - bind9-utils
      - dnsutils
    state: latest
    update_cache: true

- name: Copy template of bind9
  template:
    src: "{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
  with_items:
    - "named.conf.local"
    - "db.home.master.local"
  notify: Restart bind9
  tags:
    - bind9_config